#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupVision.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GroupVisao")]
	public partial class GroupVisionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCertificado(Certificado instance);
    partial void UpdateCertificado(Certificado instance);
    partial void DeleteCertificado(Certificado instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertEmpresa(Empresa instance);
    partial void UpdateEmpresa(Empresa instance);
    partial void DeleteEmpresa(Empresa instance);
    partial void InsertEndereco(Endereco instance);
    partial void UpdateEndereco(Endereco instance);
    partial void DeleteEndereco(Endereco instance);
    #endregion
		
		public GroupVisionDataContext() : 
				base(global::GroupVision.Data.Properties.Settings.Default.GroupVisaoConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public GroupVisionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GroupVisionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GroupVisionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GroupVisionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Certificado> Certificados
		{
			get
			{
				return this.GetTable<Certificado>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Empresa> Empresas
		{
			get
			{
				return this.GetTable<Empresa>();
			}
		}
		
		public System.Data.Linq.Table<Endereco> Enderecos
		{
			get
			{
				return this.GetTable<Endereco>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Certificado")]
	public partial class Certificado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_ID_CERTIFICADO;
		
		private string _TIPO;
		
		private System.DateTime _DATA_EMISSAO;
		
		private System.DateTime _DATA_VENCIMENTO;
		
		private string _CELULAR;
		
		private int _FK_EMPRESA;
		
		private int _ID_USUARIO_ULT_ATT;
		
		private int _DATA_ULT_ATT;
		
		private bool _ATIVO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_ID_CERTIFICADOChanging(int value);
    partial void OnPK_ID_CERTIFICADOChanged();
    partial void OnTIPOChanging(string value);
    partial void OnTIPOChanged();
    partial void OnDATA_EMISSAOChanging(System.DateTime value);
    partial void OnDATA_EMISSAOChanged();
    partial void OnDATA_VENCIMENTOChanging(System.DateTime value);
    partial void OnDATA_VENCIMENTOChanged();
    partial void OnCELULARChanging(string value);
    partial void OnCELULARChanged();
    partial void OnFK_EMPRESAChanging(int value);
    partial void OnFK_EMPRESAChanged();
    partial void OnID_USUARIO_ULT_ATTChanging(int value);
    partial void OnID_USUARIO_ULT_ATTChanged();
    partial void OnDATA_ULT_ATTChanging(int value);
    partial void OnDATA_ULT_ATTChanged();
    partial void OnATIVOChanging(bool value);
    partial void OnATIVOChanged();
    #endregion
		
		public Certificado()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_ID_CERTIFICADO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PK_ID_CERTIFICADO
		{
			get
			{
				return this._PK_ID_CERTIFICADO;
			}
			set
			{
				if ((this._PK_ID_CERTIFICADO != value))
				{
					this.OnPK_ID_CERTIFICADOChanging(value);
					this.SendPropertyChanging();
					this._PK_ID_CERTIFICADO = value;
					this.SendPropertyChanged("PK_ID_CERTIFICADO");
					this.OnPK_ID_CERTIFICADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIPO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TIPO
		{
			get
			{
				return this._TIPO;
			}
			set
			{
				if ((this._TIPO != value))
				{
					this.OnTIPOChanging(value);
					this.SendPropertyChanging();
					this._TIPO = value;
					this.SendPropertyChanged("TIPO");
					this.OnTIPOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_EMISSAO", DbType="Date NOT NULL")]
		public System.DateTime DATA_EMISSAO
		{
			get
			{
				return this._DATA_EMISSAO;
			}
			set
			{
				if ((this._DATA_EMISSAO != value))
				{
					this.OnDATA_EMISSAOChanging(value);
					this.SendPropertyChanging();
					this._DATA_EMISSAO = value;
					this.SendPropertyChanged("DATA_EMISSAO");
					this.OnDATA_EMISSAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_VENCIMENTO", DbType="Date NOT NULL")]
		public System.DateTime DATA_VENCIMENTO
		{
			get
			{
				return this._DATA_VENCIMENTO;
			}
			set
			{
				if ((this._DATA_VENCIMENTO != value))
				{
					this.OnDATA_VENCIMENTOChanging(value);
					this.SendPropertyChanging();
					this._DATA_VENCIMENTO = value;
					this.SendPropertyChanged("DATA_VENCIMENTO");
					this.OnDATA_VENCIMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CELULAR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CELULAR
		{
			get
			{
				return this._CELULAR;
			}
			set
			{
				if ((this._CELULAR != value))
				{
					this.OnCELULARChanging(value);
					this.SendPropertyChanging();
					this._CELULAR = value;
					this.SendPropertyChanged("CELULAR");
					this.OnCELULARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_EMPRESA", DbType="Int NOT NULL")]
		public int FK_EMPRESA
		{
			get
			{
				return this._FK_EMPRESA;
			}
			set
			{
				if ((this._FK_EMPRESA != value))
				{
					this.OnFK_EMPRESAChanging(value);
					this.SendPropertyChanging();
					this._FK_EMPRESA = value;
					this.SendPropertyChanged("FK_EMPRESA");
					this.OnFK_EMPRESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO_ULT_ATT", DbType="Int NOT NULL")]
		public int ID_USUARIO_ULT_ATT
		{
			get
			{
				return this._ID_USUARIO_ULT_ATT;
			}
			set
			{
				if ((this._ID_USUARIO_ULT_ATT != value))
				{
					this.OnID_USUARIO_ULT_ATTChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO_ULT_ATT = value;
					this.SendPropertyChanged("ID_USUARIO_ULT_ATT");
					this.OnID_USUARIO_ULT_ATTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_ULT_ATT", DbType="Int NOT NULL")]
		public int DATA_ULT_ATT
		{
			get
			{
				return this._DATA_ULT_ATT;
			}
			set
			{
				if ((this._DATA_ULT_ATT != value))
				{
					this.OnDATA_ULT_ATTChanging(value);
					this.SendPropertyChanging();
					this._DATA_ULT_ATT = value;
					this.SendPropertyChanged("DATA_ULT_ATT");
					this.OnDATA_ULT_ATTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATIVO", DbType="Bit NOT NULL")]
		public bool ATIVO
		{
			get
			{
				return this._ATIVO;
			}
			set
			{
				if ((this._ATIVO != value))
				{
					this.OnATIVOChanging(value);
					this.SendPropertyChanging();
					this._ATIVO = value;
					this.SendPropertyChanged("ATIVO");
					this.OnATIVOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_ID_USUARIO;
		
		private string _LOGIN;
		
		private string _SENHA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_ID_USUARIOChanging(int value);
    partial void OnPK_ID_USUARIOChanged();
    partial void OnLOGINChanging(string value);
    partial void OnLOGINChanged();
    partial void OnSENHAChanging(string value);
    partial void OnSENHAChanged();
    #endregion
		
		public Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_ID_USUARIO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PK_ID_USUARIO
		{
			get
			{
				return this._PK_ID_USUARIO;
			}
			set
			{
				if ((this._PK_ID_USUARIO != value))
				{
					this.OnPK_ID_USUARIOChanging(value);
					this.SendPropertyChanging();
					this._PK_ID_USUARIO = value;
					this.SendPropertyChanged("PK_ID_USUARIO");
					this.OnPK_ID_USUARIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGIN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LOGIN
		{
			get
			{
				return this._LOGIN;
			}
			set
			{
				if ((this._LOGIN != value))
				{
					this.OnLOGINChanging(value);
					this.SendPropertyChanging();
					this._LOGIN = value;
					this.SendPropertyChanged("LOGIN");
					this.OnLOGINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SENHA", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SENHA
		{
			get
			{
				return this._SENHA;
			}
			set
			{
				if ((this._SENHA != value))
				{
					this.OnSENHAChanging(value);
					this.SendPropertyChanging();
					this._SENHA = value;
					this.SendPropertyChanged("SENHA");
					this.OnSENHAChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Empresa")]
	public partial class Empresa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_ID_EMPRESA;
		
		private string _NOME;
		
		private string _APELIDO;
		
		private string _CELULAR;
		
		private string _TELEFNE;
		
		private string _EMAIL_CLIENTE;
		
		private string _EMAIL_ESCRITORIO;
		
		private string _EMAIL_CERTIFICADO;
		
		private string _RESPONSAVEL;
		
		private int _ID_USUARIO_ULT_ATT;
		
		private System.DateTime _DATA_ULTIMA_ATT;
		
		private bool _ATIVO;
		
		private string _CNPJ;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_ID_EMPRESAChanging(int value);
    partial void OnPK_ID_EMPRESAChanged();
    partial void OnNOMEChanging(string value);
    partial void OnNOMEChanged();
    partial void OnAPELIDOChanging(string value);
    partial void OnAPELIDOChanged();
    partial void OnCELULARChanging(string value);
    partial void OnCELULARChanged();
    partial void OnTELEFNEChanging(string value);
    partial void OnTELEFNEChanged();
    partial void OnEMAIL_CLIENTEChanging(string value);
    partial void OnEMAIL_CLIENTEChanged();
    partial void OnEMAIL_ESCRITORIOChanging(string value);
    partial void OnEMAIL_ESCRITORIOChanged();
    partial void OnEMAIL_CERTIFICADOChanging(string value);
    partial void OnEMAIL_CERTIFICADOChanged();
    partial void OnRESPONSAVELChanging(string value);
    partial void OnRESPONSAVELChanged();
    partial void OnID_USUARIO_ULT_ATTChanging(int value);
    partial void OnID_USUARIO_ULT_ATTChanged();
    partial void OnDATA_ULTIMA_ATTChanging(System.DateTime value);
    partial void OnDATA_ULTIMA_ATTChanged();
    partial void OnATIVOChanging(bool value);
    partial void OnATIVOChanged();
    partial void OnCNPJChanging(string value);
    partial void OnCNPJChanged();
    #endregion
		
		public Empresa()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_ID_EMPRESA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PK_ID_EMPRESA
		{
			get
			{
				return this._PK_ID_EMPRESA;
			}
			set
			{
				if ((this._PK_ID_EMPRESA != value))
				{
					this.OnPK_ID_EMPRESAChanging(value);
					this.SendPropertyChanging();
					this._PK_ID_EMPRESA = value;
					this.SendPropertyChanged("PK_ID_EMPRESA");
					this.OnPK_ID_EMPRESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NOME
		{
			get
			{
				return this._NOME;
			}
			set
			{
				if ((this._NOME != value))
				{
					this.OnNOMEChanging(value);
					this.SendPropertyChanging();
					this._NOME = value;
					this.SendPropertyChanged("NOME");
					this.OnNOMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELIDO", DbType="NVarChar(50)")]
		public string APELIDO
		{
			get
			{
				return this._APELIDO;
			}
			set
			{
				if ((this._APELIDO != value))
				{
					this.OnAPELIDOChanging(value);
					this.SendPropertyChanging();
					this._APELIDO = value;
					this.SendPropertyChanged("APELIDO");
					this.OnAPELIDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CELULAR", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CELULAR
		{
			get
			{
				return this._CELULAR;
			}
			set
			{
				if ((this._CELULAR != value))
				{
					this.OnCELULARChanging(value);
					this.SendPropertyChanging();
					this._CELULAR = value;
					this.SendPropertyChanged("CELULAR");
					this.OnCELULARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFNE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TELEFNE
		{
			get
			{
				return this._TELEFNE;
			}
			set
			{
				if ((this._TELEFNE != value))
				{
					this.OnTELEFNEChanging(value);
					this.SendPropertyChanging();
					this._TELEFNE = value;
					this.SendPropertyChanged("TELEFNE");
					this.OnTELEFNEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_CLIENTE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL_CLIENTE
		{
			get
			{
				return this._EMAIL_CLIENTE;
			}
			set
			{
				if ((this._EMAIL_CLIENTE != value))
				{
					this.OnEMAIL_CLIENTEChanging(value);
					this.SendPropertyChanging();
					this._EMAIL_CLIENTE = value;
					this.SendPropertyChanged("EMAIL_CLIENTE");
					this.OnEMAIL_CLIENTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_ESCRITORIO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL_ESCRITORIO
		{
			get
			{
				return this._EMAIL_ESCRITORIO;
			}
			set
			{
				if ((this._EMAIL_ESCRITORIO != value))
				{
					this.OnEMAIL_ESCRITORIOChanging(value);
					this.SendPropertyChanging();
					this._EMAIL_ESCRITORIO = value;
					this.SendPropertyChanged("EMAIL_ESCRITORIO");
					this.OnEMAIL_ESCRITORIOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_CERTIFICADO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL_CERTIFICADO
		{
			get
			{
				return this._EMAIL_CERTIFICADO;
			}
			set
			{
				if ((this._EMAIL_CERTIFICADO != value))
				{
					this.OnEMAIL_CERTIFICADOChanging(value);
					this.SendPropertyChanging();
					this._EMAIL_CERTIFICADO = value;
					this.SendPropertyChanged("EMAIL_CERTIFICADO");
					this.OnEMAIL_CERTIFICADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESPONSAVEL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string RESPONSAVEL
		{
			get
			{
				return this._RESPONSAVEL;
			}
			set
			{
				if ((this._RESPONSAVEL != value))
				{
					this.OnRESPONSAVELChanging(value);
					this.SendPropertyChanging();
					this._RESPONSAVEL = value;
					this.SendPropertyChanged("RESPONSAVEL");
					this.OnRESPONSAVELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_USUARIO_ULT_ATT", DbType="Int NOT NULL")]
		public int ID_USUARIO_ULT_ATT
		{
			get
			{
				return this._ID_USUARIO_ULT_ATT;
			}
			set
			{
				if ((this._ID_USUARIO_ULT_ATT != value))
				{
					this.OnID_USUARIO_ULT_ATTChanging(value);
					this.SendPropertyChanging();
					this._ID_USUARIO_ULT_ATT = value;
					this.SendPropertyChanged("ID_USUARIO_ULT_ATT");
					this.OnID_USUARIO_ULT_ATTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATA_ULTIMA_ATT", DbType="Date NOT NULL")]
		public System.DateTime DATA_ULTIMA_ATT
		{
			get
			{
				return this._DATA_ULTIMA_ATT;
			}
			set
			{
				if ((this._DATA_ULTIMA_ATT != value))
				{
					this.OnDATA_ULTIMA_ATTChanging(value);
					this.SendPropertyChanging();
					this._DATA_ULTIMA_ATT = value;
					this.SendPropertyChanged("DATA_ULTIMA_ATT");
					this.OnDATA_ULTIMA_ATTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ATIVO", DbType="Bit NOT NULL")]
		public bool ATIVO
		{
			get
			{
				return this._ATIVO;
			}
			set
			{
				if ((this._ATIVO != value))
				{
					this.OnATIVOChanging(value);
					this.SendPropertyChanging();
					this._ATIVO = value;
					this.SendPropertyChanged("ATIVO");
					this.OnATIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNPJ", DbType="NVarChar(50)")]
		public string CNPJ
		{
			get
			{
				return this._CNPJ;
			}
			set
			{
				if ((this._CNPJ != value))
				{
					this.OnCNPJChanging(value);
					this.SendPropertyChanging();
					this._CNPJ = value;
					this.SendPropertyChanged("CNPJ");
					this.OnCNPJChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Endereco")]
	public partial class Endereco : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PK_ID_ENDERECO;
		
		private string _LOGRADOURO;
		
		private string _CIDADE;
		
		private string _ESTADO;
		
		private string _CEP;
		
		private string _COMPLEMENTO;
		
		private int _FK_EMPRESA;
		
		private string _BAIRRO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_ID_ENDERECOChanging(int value);
    partial void OnPK_ID_ENDERECOChanged();
    partial void OnLOGRADOUROChanging(string value);
    partial void OnLOGRADOUROChanged();
    partial void OnCIDADEChanging(string value);
    partial void OnCIDADEChanged();
    partial void OnESTADOChanging(string value);
    partial void OnESTADOChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnCOMPLEMENTOChanging(string value);
    partial void OnCOMPLEMENTOChanged();
    partial void OnFK_EMPRESAChanging(int value);
    partial void OnFK_EMPRESAChanged();
    partial void OnBAIRROChanging(string value);
    partial void OnBAIRROChanged();
    #endregion
		
		public Endereco()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_ID_ENDERECO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PK_ID_ENDERECO
		{
			get
			{
				return this._PK_ID_ENDERECO;
			}
			set
			{
				if ((this._PK_ID_ENDERECO != value))
				{
					this.OnPK_ID_ENDERECOChanging(value);
					this.SendPropertyChanging();
					this._PK_ID_ENDERECO = value;
					this.SendPropertyChanged("PK_ID_ENDERECO");
					this.OnPK_ID_ENDERECOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGRADOURO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LOGRADOURO
		{
			get
			{
				return this._LOGRADOURO;
			}
			set
			{
				if ((this._LOGRADOURO != value))
				{
					this.OnLOGRADOUROChanging(value);
					this.SendPropertyChanging();
					this._LOGRADOURO = value;
					this.SendPropertyChanged("LOGRADOURO");
					this.OnLOGRADOUROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIDADE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CIDADE
		{
			get
			{
				return this._CIDADE;
			}
			set
			{
				if ((this._CIDADE != value))
				{
					this.OnCIDADEChanging(value);
					this.SendPropertyChanging();
					this._CIDADE = value;
					this.SendPropertyChanged("CIDADE");
					this.OnCIDADEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ESTADO
		{
			get
			{
				return this._ESTADO;
			}
			set
			{
				if ((this._ESTADO != value))
				{
					this.OnESTADOChanging(value);
					this.SendPropertyChanging();
					this._ESTADO = value;
					this.SendPropertyChanged("ESTADO");
					this.OnESTADOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPLEMENTO", DbType="NVarChar(50)")]
		public string COMPLEMENTO
		{
			get
			{
				return this._COMPLEMENTO;
			}
			set
			{
				if ((this._COMPLEMENTO != value))
				{
					this.OnCOMPLEMENTOChanging(value);
					this.SendPropertyChanging();
					this._COMPLEMENTO = value;
					this.SendPropertyChanged("COMPLEMENTO");
					this.OnCOMPLEMENTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_EMPRESA", DbType="Int NOT NULL")]
		public int FK_EMPRESA
		{
			get
			{
				return this._FK_EMPRESA;
			}
			set
			{
				if ((this._FK_EMPRESA != value))
				{
					this.OnFK_EMPRESAChanging(value);
					this.SendPropertyChanging();
					this._FK_EMPRESA = value;
					this.SendPropertyChanged("FK_EMPRESA");
					this.OnFK_EMPRESAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAIRRO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BAIRRO
		{
			get
			{
				return this._BAIRRO;
			}
			set
			{
				if ((this._BAIRRO != value))
				{
					this.OnBAIRROChanging(value);
					this.SendPropertyChanging();
					this._BAIRRO = value;
					this.SendPropertyChanged("BAIRRO");
					this.OnBAIRROChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
